# Generated by Django 4.1.1 on 2022-09-28 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='text',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
