# Generated by Django 4.1.3 on 2022-11-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_answer_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='answers',
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(),
        ),
    ]
