# Generated by Django 4.1.3 on 2022-11-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_alter_diploma_continuous_training_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diploma',
            name='continuous_training_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
