# Generated by Django 4.1.3 on 2022-11-07 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0006_candidate_question1_candidate_question2_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answer',
            new_name='QuestionCandidate',
        ),
        migrations.RenameModel(
            old_name='Question',
            new_name='QuestionTemplate',
        ),
    ]
