# Generated by Django 4.1.3 on 2022-11-07 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0007_rename_answer_questioncandidate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='question1',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='question2',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='question3',
        ),
    ]
