# Generated by Django 4.1.3 on 2022-11-07 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0008_remove_candidate_question1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'verbose_name': 'Candidat'},
        ),
        migrations.AlterModelOptions(
            name='diploma',
            options={'verbose_name': 'Diplôme'},
        ),
        migrations.AlterModelOptions(
            name='questioncandidate',
            options={'verbose_name': 'Réponse des candidats', 'verbose_name_plural': 'Réponses des candidats'},
        ),
        migrations.AlterModelOptions(
            name='questiontemplate',
            options={'verbose_name': 'Modèle de question', 'verbose_name_plural': 'Modèles de question'},
        ),
        migrations.AddField(
            model_name='diploma',
            name='continuous_training_file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Attestation de formation continue'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='birth_date',
            field=models.DateField(verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Courriel'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='diploma',
            name='continuous_training_date',
            field=models.DateField(blank=True, help_text='Date de la dernière formation continue, si applicable', null=True, verbose_name='Dernière formation continue'),
        ),
        migrations.AlterField(
            model_name='diploma',
            name='date',
            field=models.DateField(verbose_name="Date d'obtention"),
        ),
        migrations.AlterField(
            model_name='diploma',
            name='diploma_file',
            field=models.FileField(upload_to='', verbose_name='Diplôme'),
        ),
        migrations.AlterField(
            model_name='diploma',
            name='type',
            field=models.CharField(choices=[('PSC1', 'Prévention et Secours Civiques de niveau 1'), ('SST', 'Sauveteur Secouriste du Travail'), ('PSE1', 'Premiers Secours en Equipe de niveau 1'), ('PSE2', 'Premiers Secours en Equipe de niveau 2'), ('PAE FPS', "Pédagogie Appliquée à l'emploi de Formateur Premiers Secours"), ('PAE FPSC', "Pédagogie Appliquée à l'emploi de Formateur Prévention et Secours Civiques"), ('PAE FF', "Pédagogie Appliquée à l'emploi de Formateur de Formateur"), ('CEAF', "Conception et Encadrement d'Activité de Formation")], help_text="Seuls les diplômes reconnus par le ministère de l'Intérieur sont disponibles", max_length=10, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='questioncandidate',
            name='question',
            field=models.CharField(max_length=200, verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='questioncandidate',
            name='text',
            field=models.TextField(verbose_name='Réponse'),
        ),
    ]
