# Generated by Django 4.1.3 on 2022-11-07 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0009_alter_candidate_options_alter_diploma_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diploma',
            name='type',
            field=models.CharField(choices=[('Secourisme grand public', (('PSC1', 'PSC1 - Prévention et Secours Civiques de niveau 1'), ('SST', 'SST - Sauveteur Secouriste du Travail'))), ('Secours opérationnel', (('PSE1', 'PSE1 - Premiers Secours en Equipe de niveau 1'), ('PSE2', 'PSE2 - Premiers Secours en Equipe de niveau 2'))), ('Formation', (('PAE FPS', "PAE FPS - Pédagogie Appliquée à l'emploi de Formateur Premiers Secours"), ('PAE FPSC', "PAE FPSC - Pédagogie Appliquée à l'emploi de Formateur Prévention et Secours Civiques"), ('PAE FF', "PAE FF - Pédagogie Appliquée à l'emploi de Formateur de Formateur"), ('CEAF', "CEAF - Conception et Encadrement d'Activité de Formation")))], help_text="Seuls les diplômes reconnus par le ministère de l'Intérieur sont disponibles", max_length=10, verbose_name='Type'),
        ),
    ]
