# Generated by Django 4.1.6 on 2023-02-02 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0011_candidate_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='update',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Dernière mise à jour'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('in_creation', 'En cours de création'), ('completed', 'Dossier complété'), ('completion_confirmed', 'Dossier complet'), ('meeting_proposed', "Date d'entretien proposée"), ('waiting_meeting', "En attente de l'entretien"), ('waiting_candidate', 'En attente de retour du candidat'), ('candidate_confirmed', 'En attente de retour du recrutement'), ('rejected', 'Candidature refusée'), ('waiting_creation', 'En attente de la création des accès'), ('waiting_training', "En attente de l'ajout des compétences"), ('closure', 'Dossier clôturé')], default='in_creation', max_length=100),
        ),
    ]
