# Generated by Django 4.1.6 on 2023-02-02 23:02

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0012_candidate_update_alter_candidate_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='update',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=django_fsm.FSMField(default='created', max_length=50),
        ),
    ]
