# Generated by Django 4.1.6 on 2023-02-02 23:49

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0013_remove_candidate_update_alter_candidate_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=django_fsm.FSMField(default='record_created', max_length=50),
        ),
    ]
