# Generated by Django 4.1.7 on 2023-04-05 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0015_candidate_update_alter_candidate_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('record_created', 'Dossier créé'), ('record_completed', 'Dossier complété'), ('record_accepted', 'Dossier complet'), ('meeting_proposed', "Date d'entretien proposée"), ('waiting_meeting', "En attente de l'entretien"), ('waiting_candidate', 'En attente de retour du candidat'), ('candidate_confirmed', 'En attente de retour du recrutement'), ('rejected', 'Candidature refusée'), ('waiting_creation', 'En attente de la création des accès'), ('waiting_training', "En attente de l'ajout des compétences"), ('closure', 'Dossier clôturé')], default='record_created', max_length=100, verbose_name='Statut'),
        ),
    ]
