# Generated by Django 4.1.7 on 2023-04-05 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0017_alter_candidate_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'permissions': (('record_completion', {'label': 'Marquer comme complet'}), ('record_rejection', {'label': 'Marquer comme incomplet'}), ('record_acception', {'label': 'Accepter le dossier'}), ('meeting_proposition', {'label': 'Proposer un entretien'}), ('meeting_rejection', {'label': "Refuser la date d'entretien"}), ('meeting_acception', {'label': "Accepter la date d'entretien"}), ('meeting_absence', {'label': "Absent à l'entretien"}), ('meeting_presence', {'label': "Présent à l'entretien"}), ('candidate_resignation', {'label': 'Renoncer à la candidature'}), ('candidate_rejection', {'label': 'Rejeter la candidature'}), ('candidate_confirmation', {'label': 'Confirmer la candidature'}), ('candidate_acception', {'label': 'Accepter la candidature'}), ('account_creation', {'label': 'Compte créé'}), ('closing', {'label': 'Clôre le dossier'}), ('destruction', {'label': 'Destruction du dossier'})), 'verbose_name': 'Candidat'},
        ),
    ]
